name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.13.0
        working-directory: ./modular_monolith

      - name: Build
        run: |
          npm cache clean --force
          npm install --only=prod
          npm run build

      - name: Tests
        run: |
          npm test
